version: '3.8'

services:
  web:
    # في Azure لا يمكن استخدام build: . بل يجب تحديد مسار الصورة المرفوعة
    image: <your-azure-container-registry-name>.azurecr.io/library-app:latest
    ports:
      - "8000:8000"
    # يتم إلغاء الـ volumes المحلية لأننا سنعتمد على التخزين السحابي
    restart: always
